/* 
Query Purpose:
---------------
This query calculates the payback period for marketing cohorts. 
For each (cohort_date, campaign_id) within the last 90 days, it determines:
 - The earliest date when cumulative margin generated by that cohort meets or exceeds the total campaign spend (payback date).
 - The number of days between cohort acquisition and payback (payback_days).
 - Additional context: cumulative margin, spend, and profit made at payback.
*/

DECLARE @EndDate DATE  = CAST(GETDATE() AS DATE);  
DECLARE @StartDate DATE = DATEADD(DAY, -90, @EndDate);  

WITH acq AS (   -- 1. Define acquisition cohorts
    SELECT 
        user_id,
        campaign_id,
        install_time AS cohort_date
    FROM neo.users 
    WHERE install_time >= @StartDate 
      AND install_time < DATEADD(DAY, 1, @EndDate)
),

daily_revenue AS (   -- 2. Aggregate margin per cohort per revenue day
    SELECT
        a.cohort_date,
        a.campaign_id,
        r.txn_time AS revenue_date,
        SUM(r.margin) AS margin
    FROM neo.revenue r
    INNER JOIN acq a 
        ON a.user_id = r.user_id
    WHERE r.txn_time >= a.cohort_date 
      AND r.txn_time < DATEADD(DAY, 1, @EndDate)
    GROUP BY 
        a.cohort_date,
        a.campaign_id,
        r.txn_time
),

spend_by_cohort AS (   -- 3. Total spend per cohort (cohort_date + campaign)
    SELECT
        spend.date AS cohort_date,
        campaign_id,
        SUM(spend) AS total_spend
    FROM neo.spend
    WHERE spend.date >= @StartDate 
      AND spend.date < DATEADD(DAY, 1, @EndDate) 
    GROUP BY 
        spend.date,
        campaign_id
),

cummulative AS (   -- 4. Compute running cumulative margin for each cohort
    SELECT 
        d.cohort_date,
        d.campaign_id,
        d.revenue_date,
        d.margin,
        SUM(d.margin) OVER (
            PARTITION BY d.cohort_date, d.campaign_id 
            ORDER BY d.revenue_date
        ) AS cumulative_margin,
        s.total_spend
    FROM daily_revenue d  
    INNER JOIN spend_by_cohort s 
        ON s.cohort_date = d.cohort_date 
       AND s.campaign_id = d.campaign_id
),

first_hit AS (   -- 5. Find first date where cumulative margin >= spend
    SELECT 
        cohort_date,
        campaign_id,
        MIN(revenue_date) AS payback_date
    FROM cummulative
    WHERE cumulative_margin >= total_spend
    GROUP BY 
        cohort_date,
        campaign_id
)

-- 6. Return aligned results: payback date, payback_days, margin, spend, profit
SELECT 
    c.cohort_date,
    c.campaign_id,
    f.payback_date,
    DATEDIFF(DAY, c.cohort_date, f.payback_date) AS payback_days,
    c.cumulative_margin AS cum_margin_at_payback,
    c.total_spend AS spend_at_payback,
    c.cumulative_margin - c.total_spend AS profit_made
FROM first_hit f
INNER JOIN cummulative c  
    ON c.cohort_date = f.cohort_date
   AND c.campaign_id = f.campaign_id
   AND c.revenue_date = f.payback_date
ORDER BY 
    c.cohort_date,
    c.campaign_id;
-- End of Query
